//{{NO_DEPENDENCIES}}
// Included file generated by Microsoft Visual C++.
// For use by OpenGL.rc
//
#define IDR_VERTEX                      101
#define IDR_FRAGMENT                    102
#define IDR_JPG1                        103
#define IDR_JPG2                        104
#define IDR_JPG3                        105
#define IDI_ICON1                       106
#define IDR_JPG4                        107

#define IDR_JPG5                        108
#define IDR_SKY_VERTEX                  109
#define IDR_SKY_FRAGMENT                110
#define IDR_FRONT                       111
#define IDR_LEFT                        112
#define IDR_RIGHT                       113
#define IDR_BACK                        114
#define IDR_TOP                         115
#define IDR_bottom                      116

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
